### Local API Tests

### Get all contacts
GET http://localhost:3000/contacts

### Get one contact (replace with actual ID)
GET http://localhost:3000/contacts/682e23e8cc8f14903304a544

### Welcome message
GET http://localhost:3000/


### Render API Tests

### Get all contacts
GET https://cse-341-hs48.onrender.com/contacts

### Get one contact (replace with actual ID)
GET https://cse-341-hs48.onrender.com/contacts/682e23e8cc8f14903304a544

### Welcome message
GET https://cse-341-hs48.onrender.com/
